# This is a basic workflow to help you get started with Actions

name: Build and deploy to DigitalOcean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo 'Connected to the deployment server'
            mkdir GithubDeploy
            cd GithubDeploy
            git clone https://github.com/koxx4/SimpleWorkouServer.git
            cd SimpleWorkoutServer
            git pull origin main
            echo 'Cloned production ready code onto the server'
            echo 'Building project with maven...'
            ./mvnw spring-boot:run
